---
title: "R Notebook"
output: html_notebook
---
# 25 February 2020

## Loading in SD Data
```{r, message= FALSE}
Kobe.Ian = read_excel('Play Exp 1 (SD) Data (1).xlsx', sheet = 'P1_Kobe&Ian')
Sally.Vanya = read_excel('Play Exp 1 (SD) Data (1).xlsx', sheet = 'P2_Sally&Vanya')
Rocky.Oaky = read_excel('Play Exp 1 (SD) Data (1).xlsx', sheet = 'P3_Rocky&Oaky')
Rosie.Carlie = read_excel('Play Exp 1 (SD) Data (1).xlsx', sheet = 'P4_Rosie&Carlie')
Koda.Ava = read_excel('Play Exp 1 (SD) Data (1).xlsx', sheet = 'P5_Koda&Ava')
Kodi.Kaia = read_excel('Play Exp 1 (SD) Data (1).xlsx', sheet = 'P6_Kodi & Kaia')
Dax.Fiona = read_excel('Play Exp 1 (SD) Data (1).xlsx', sheet = 'P7_Dax & Fiona')
Mason.Coffee = read_excel('Play Exp 1 (SD) Data (1).xlsx', sheet = 'P8_Mason&Coffee')
Gunner.Cato = read_excel('Play Exp 1 (SD) Data (1).xlsx', sheet = 'P9_Gunner&Cato')
Misha.Houston = read_excel('Play Exp 1 (SD) Data (1).xlsx', sheet = 'P10_Misha&Houston')
Rev.Blitz = read_excel('Play Exp 1 (SD) Data (1).xlsx', sheet = 'P11_Rev&Blitz')
Jude.Luna = read_excel('Play Exp 1 (SD) Data (1).xlsx', sheet = 'P12_Jude&Luna')
```

## Descriptives for the SD Data

### Kobe & Ian
```{r}
library(mosaic)
favstats(~Kobe.Ian$SD)
gf_point(Kobe.Ian$SD~Kobe.Ian$Session)
gf_line(Kobe.Ian$SD~Kobe.Ian$Session) %>% gf_line(Kobe.Ian$`S-Delta`~Kobe.Ian$Session, color = 'red') %>% gf_labs(title = 'Kobe & Ian SD v. S-Delta Experiment', x = 'Session' , y = 'Time Played (Seconds)')
```
### Sally & Vanya
```{r}
library(mosaic)
favstats(~Sally.Vanya$`Percent of Scored Intervals in SD...2`)
favstats(~Sally.Vanya$`Percent of Scored Intervals in S-delta...3`)
gf_line(Sally.Vanya$`Percent of Scored Intervals in SD...2`~Sally.Vanya$Session...1) %>% gf_line(Sally.Vanya$`Percent of Scored Intervals in S-delta...3`~Sally.Vanya$Session...1, color = 'red') %>% gf_labs(title = 'Sally & Vanya SD v. S-Delta Experiment', x = 'Session', y = 'Time Played (Seconds)')
```
### Rocky & Oaky
```{r}
library(mosaic)
favstats(~Rocky.Oaky$`SD (Attention)`)
gf_line(Rocky.Oaky$`SD (Attention)`~Rocky.Oaky$Session...2) %>% gf_line(Rocky.Oaky$`S-Delta (No Attention)`~Rocky.Oaky$Session...2, color = 'red') %>% gf_labs(title =  'Rocky & Oaky SD v. S-Delta Experiment', x = 'Session', y = 'Time Played (Seconds)')
```
### Rosie & Carlie
```{r}
library(mosaic)
favstats(~Rosie.Carlie$`SD (Attention)`)
gf_line(Rosie.Carlie$`SD (Attention)`~Rosie.Carlie$Session...2) %>% gf_line(Rosie.Carlie$`S-Delta (No Attention)`~Rosie.Carlie$Session...2, color = 'red') %>% gf_labs(title = 'Rosie & Carlie SD v. S-Delta Experiment', x = 'Session', y = 'Time Played (Seconds)')
```
### Koda & Ava
```{r}
library(mosaic)
favstats(~Koda.Ava$`SD (Attention)`)
gf_line(Koda.Ava$`SD (Attention)`~Koda.Ava$Session) %>% gf_line(Koda.Ava$`S-Delta (No Attention)`~Koda.Ava$Session, color = 'red') %>% gf_labs(title = 'Koda & Ava SD v. S-Delta Experiment', x = 'Session', y = 'Time Played (Seconds)')
```
### Kodi & Kaia
```{r}
library(mosaic)
favstats(~Kodi.Kaia$`SD (Attention)`)
favstats(~Kodi.Kaia$`S-Delta (No Attention)`)
gf_line(Kodi.Kaia$`SD (Attention)`~Kodi.Kaia$Session...2) %>% gf_line(Kodi.Kaia$`S-Delta (No Attention)`~Kodi.Kaia$Session...2, color = 'red') %>% gf_labs(title = 'Kodi & Kaia SD v. S-Delta Experiment', x = 'Session', y = 'Time Played (Seconds)')
```






## Loading in EO Data

```{r}
Kobe.Ian.EO = read_excel('Play Exp 2 (EO) Data (1).xlsx', sheet = 'P1_Kobe&Ian')
Sally.Vanya.EO = read_excel('Play Exp 2 (EO) Data (1).xlsx', sheet = 'P2_Sally&Vanya')
Rocky.Oaky.EO = read_excel('Play Exp 2 (EO) Data (1).xlsx', sheet = 'P3_Rocky&Oaky')
Rosie.Carlie.EO = read_excel('Play Exp 2 (EO) Data (1).xlsx', sheet = 'P4_Rosie&Carlie')
Koda.Ava.EO = read_excel('Play Exp 2 (EO) Data (1).xlsx', sheet = 'P5_Koda&Ava')
Kodi.Kaia.EO = read_excel('Play Exp 2 (EO) Data (1).xlsx', sheet = 'P6_Kodi & Kaia')
```

## Descriptives for EO Data

### Kobe & Ian

### Sally & Vanya

### Rocky & Oaky
```{r}
par(mfrow = c(1,2))
barplot(c(0, 0, 4, 1), names.arg = c('0', '30', '120', '>360'), ylim = c(0, 4), xlab = 'Level of Owner Deprivation (Min)', ylab = 'Time Played (Seconds)', col = rainbow(4))
barplot(c(164, 0, 28, 99), names.arg = c('0', '30', '120', '>360'), ylim = c(0, 164), xlab = 'Level of Owner Deprivation (Min)', ylab = 'Time Played (Seconds)', col = rainbow(4))
```

### Rosie & Carlie
```{r}
par(mfrow = c(1,2))
barplot(c(4, 34, 12, 3), names.arg = c('0', '30', '120', '>360'), ylim = c(0, 34), xlab = 'Level of Owner Deprivation (Min)', ylab = 'Time Played (Seconds)', col = rainbow(4))
barplot(c(9, 19, 21, 6), names.arg = c('0', '30', '120', '>360'), ylim = c(0, 21), xlab = 'Level of Owner Deprivation (Min)', ylab = 'Time Played (Seconds)', col = rainbow(4))
```

### Kodi & Kaia
```{r}
par(mfrow = c(1,2))
barplot(c(0, 0, 0, 0), names.arg = c('0', '30', '120', '>360'), ylim = c(0, 0), xlab = 'Level of Owner Deprivation (Min)', ylab = 'Time Played (Seconds)', col = rainbow(4))
barplot(c(0, 0, 0, 0), names.arg = c('0', '30', '120', '>360'), ylim = c(0, 0), xlab = 'Level of Owner Deprivation (Min)', ylab = 'Time Played (Seconds)', col = rainbow(4))
```

## Loading in Reinforced Data

```{r}
Kobe.Ian.Rein = read_excel('Play Exp 3 (Reinforcer) Data (1).xlsx', sheet = 'P1_Kobe&Ian')
Sally.Vanya.Rein = read_excel('Play Exp 3 (Reinforcer) Data (1).xlsx', sheet = 'P2_Sally&Vanya')
Rocky.Oaky.Rein = read_excel('Play Exp 3 (Reinforcer) Data (1).xlsx', sheet = 'P3_Rocky&Oaky')
Rosie.Carlie.Rein = read_excel('Play Exp 3 (Reinforcer) Data (1).xlsx', sheet = 'P4_Rosie&Carlie')
Jude.Luna.Rein = read_excel('Play Exp 3 (Reinforcer) Data (1).xlsx', sheet = 'P5_Jude&Luna')
Kodi.Kaia.Rein = read_excel('Play Exp 3 (Reinforcer) Data (1).xlsx', sheet = 'P6_Kodi & Kaia')
```

## Descriptives for Reinforced Data

### Kobe & Ian

### Sally & Vanya
```{r}
favstats(Sally.Vanya.Rein$`Attention Control`)
favstats(Sally.Vanya.Rein$`Attention Test`)
favstats(Sally.Vanya.Rein$Alone)
gf_line(Sally.Vanya.Rein$`Attention Control`~Sally.Vanya.Rein$Session) %>% gf_line(Sally.Vanya.Rein$`Attention Test`~Sally.Vanya.Rein$Session, color = 'red') %>% gf_line(Sally.Vanya.Rein$Alone~Sally.Vanya.Rein$Session, color = 'blue') %>% gf_labs(title = 'Sally & Vanya Reinforcer Experiment', x = 'Session', y = 'Time Played (Seconds)')
```

### Rocky & Oaky

```{r}
favstats(Rocky.Oaky.Rein$`Attention Control`)
favstats(Rocky.Oaky.Rein$`Attention Test`)
favstats(Rocky.Oaky.Rein$Alone)
gf_line(Rocky.Oaky.Rein$`Attention Control`~Rocky.Oaky.Rein$Session) %>% gf_line(Rocky.Oaky.Rein$`Attention Test`~Rocky.Oaky.Rein$Session, color = 'red') %>% gf_line(Rocky.Oaky.Rein$Alone~Rocky.Oaky.Rein$Session, color = 'blue') %>% gf_labs(title = 'Rocky & Oaky Reinforcer Experiment', x = 'Session', y = 'Time Played (Seconds)')
```

# 3 March 2020

### Rosie & Carlie

```{r}
favstats(Rosie.Carlie.Rein$`Attention Control`)
favstats(Rosie.Carlie.Rein$`Attention Test`)
favstats(Rosie.Carlie.Rein$Alone)
gf_line(Rosie.Carlie.Rein$`Attention Control`~Rosie.Carlie.Rein$Session) %>% gf_line(Rosie.Carlie.Rein$`Attention Test`~Rosie.Carlie.Rein$Session, color = 'red') %>% gf_line(Rosie.Carlie.Rein$Alone~Rosie.Carlie.Rein$Session, color = 'blue') %>% gf_labs(title = 'Rosie & Carlie Reinforcer Experiment', x = 'Session', y = 'Time Played (Seconds)')
```

### Jude & Luna

### Kodi & Kaia

```{r}
favstats(Kodi.Kaia.Rein$`Attention Control`)
favstats(Kodi.Kaia.Rein$`Attention Test`)
favstats(Kodi.Kaia.Rein$Alone)
gf_line(Kodi.Kaia.Rein$`Attention Control`~Kodi.Kaia.Rein$Session) %>% gf_line(Kodi.Kaia.Rein$`Attention Test`~Kodi.Kaia.Rein$Session, color = 'red') %>% gf_line(Kodi.Kaia.Rein$Alone~Kodi.Kaia.Rein$Session, color = 'blue') %>% gf_labs(title = 'Kodi & Kaia Reinforcer Experiment', x = 'Session', y = 'Time Played (Seconds)')
```
```{r}


```


